### ISSUE TITLE
nevermore does not gain souls when attacking nor when enemy heroes are around

### ISSUE THREAD

**Issue by lmk1988** [fcalife/dota_imba#102]
I'm not sure if the souls are to be added to `modifier_souls` or `modifier_souls_dummy`
I am also quite confused between the two

**Comment by NateR124** [comment]
What color was the hair of the enemy heroes?

**Comment by lmk1988** [comment]
Oh right. Ha, I was trying to figure out why it wasn't increasing with lina. That was really the issue.
Thanks for the reminder.
