### ISSUE TITLE
Games can be paused and unpaused with no limit

### ISSUE THREAD

**Issue by Shushishtok** [fcalife/dota_imba#180]
Title.

People abuse this mechanic that allows them to keep pausing the games, ruining it for the rest of the players, because they think they're funny little retard kids.

**Comment by AtroCty** [comment]
We have to wait until Valve fixes this.

**Comment by brandonsturgeon** [comment]
Jeeze. That sucks.

I know a guy who made a bot with the sole intention of pausing imba games.

It runs all the time and automatically joins imba games to permanently pause them.

**Comment by Shushishtok** [comment]
No idea why the hell someone would even WANT to do something like, except for trying to be funny, which he fails even in that.
