### ISSUE TITLE
Discordapp link is broken (i.e. can't join channel)

### ISSUE THREAD

**Issue by ValentinNikolaev** [fcalife/dota_imba#202]
expired or has error. Please, check it. Thank's

**Comment by Shushishtok** [comment]
Which Discord link - the dev one or the regular one?

**Comment by ValentinNikolaev** [comment]
@Shushishtok I mean at README. I just wanted to join imba dev society and ooops, can't ^_^

This link https://discord.gg/gUzvJ4W

**Comment by Shushishtok** [comment]
I'll update it when I get home. In the meantime, use this link to come in.
https://discord.gg/ZDHYKVb

**Comment by Shushishtok** [comment]
Updated Readme to include the new link.
