### ISSUE TITLE
Unable to disable DotaTalentChangedItemToast

### ISSUE THREAD

**Issue by lmk1988** [fcalife/dota_imba#211]
When you upgrade an ability talent on a hero created using -createhero, dota shows a toast message showing the ability upgraded. However the level shown is using the default dota talent level instead of dota imba talent levels.

There is no way to disable it now
- No documentation on the panel
- panel is only created and then destroyed upon upgrading the talent (hence unable to apply any sort of pre-appear fixes)

**Comment by lmk1988** [comment]
![image](https://cloud.githubusercontent.com/assets/4424781/26499041/c0883bd8-4263-11e7-9355-1c50c3d6a2d2.png)

meanwhile it looks like this for spectators

**Comment by Shushishtok** [comment]
Talent manager looks like it's working perfectly for spectators as well. The Dota Talent toast thing is.. ignorable, to be honest. Closing issue.
