### ISSUE TITLE
Mekansm and Greaves spell power scale

### ISSUE THREAD

**Issue by Shushishtok** [fcalife/dota_imba#221]
Mekansm and Greaves' healing active should scale with the caster's spell power.

**Comment by X-TheDark** [comment]
Seems to already be the case with Mekansm, and Firetoad fixed Greaves in commit https://github.com/fcalife/dota_imba/commit/3ae484c71c543f6d735d370d24a1b08c124fe9a2

**Comment by Shushishtok** [comment]
Awesome then!
