### ISSUE TITLE
Server crash caused by nil reference to "nether ward" ability while user is affected by nether ward debuff 

### ISSUE THREAD

**Issue by NateR124** [fcalife/dota_imba#295]
User said their game crashed with the following error message:
[VScript] Script Runtime Error: ...15357\440115357.vpk:scripts\vscripts\hero\hero_pugna.lua:617: attempt to index field 'ability' (a nil value)

If you look, this is the first time the netherward debuff modifier tries to reference self:GetAbility(), which means it didn't correctly have a reference to the ability when created.

My current best guesses are that it is related to either:
A) the sticky time of the debuff that lasts beyond the duration of the netherward itself,
B) something related to hellblade, or any other mechanic that allows someone to transfer a debuff like nethewards to an enemy
C) Something related to applying break to pugna
D) something related to pugna's talent that improves the mana damage rate.

**Comment by Shushishtok** [comment]
Added some safeguard. Closing for now.
