### ISSUE TITLE
Battle hunger never applies to enemy, and Axe never loses movement speed stack

### ISSUE THREAD

**Issue by NateR124** [fcalife/dota_imba#296]
For whatever reason when Axe applies battle hunger on an enemy, they don't receive the debuff. In addition, this causes axe to never lose the "Battle hunger" stack buff until he dies, allowing him to gather up a lot of move speed very quickly

**Comment by sercankd** [comment]
5104b34dac6fe115e87a19cef4f460477cec553c

**Comment by Shushishtok** [comment]
Fixed.
