### ISSUE TITLE
Several LUA errors

### ISSUE THREAD

**Issue by sercankd** [fcalife/dota_imba#310]
- [x] tower_abilities.lua:850: attempt to index field 'ability' (a nil value)
- [x] tower_abilities.lua:3744 index field 'ability' a nil value
- [x] tower_abilities.lua:2223 index field 'ability' a nil value
- [x] tower_abilities.lua:2008 index field 'ability' a nil value
- [x] item_satanic.lua:45 AddNewModifier a nil value
- [ ] hero_lycan.lua:937 AddNewModifier a nil value
- [ ] hero_lycan.lua:956 RemoveModifierByName a nil value
- [ ] hero_crystal_maiden.lua:614 GetManaPercent a nil value
- [ ] item_vladmir.lua:124: attempt to index a nil value

**Comment by lmk1988** [comment]
![image](https://cloud.githubusercontent.com/assets/4424781/26454788/ad384efc-419a-11e7-9dae-bc97918a2ee6.png)

**Comment by lmk1988** [comment]
[VScript] Script Runtime Error: ...7\440115357.vpk:scripts\vscripts\hero\hero_magnataur.lua:976: attempt to index global 'caster' (a nil value)
stack traceback:
