### ISSUE TITLE
Some missing modifier descriptions

### ISSUE THREAD

**Issue by lmk1988** [fcalife/dota_imba#323]
**Enigma gravity well on units missing description**
- [x] Enigma casting gravity well on units will apply a modifier, however the modifier is missing descriptions

**Tiny tossed unit**
- [x] Tossed unit from tiny's toss do not display description

**Comment by Shushishtok** [comment]
Tossed unit's modifier can be hidden. There is no need to show it.

**Comment by Shushishtok** [comment]
Fixed.
