### ISSUE TITLE
Stasis Trap still explode after destroyed.

### ISSUE THREAD

**Issue by AtroCty** [fcalife/dota_imba#336]
Reported by HulluPoro: 
Steps to reproduce: 1. Place Stasis Trap
2. Destroy Stasis Trap
3. Enemy Runs to the place the Stasis Trap was
Expected Result:  Stasis Trap is destroyed so no root.
Actual Result: an invisible and untargetable Stasis Trap triggers the root

https://cdn.discordapp.com/attachments/317271861966929921/317306852411047938/trigger_mines.png

**Comment by Shushishtok** [comment]
Fixed.
