### ISSUE TITLE
Radiance Aura icon is invisible on Enemies

### ISSUE THREAD

**Issue by AtroCty** [fcalife/dota_imba#337]
Reported by HulluPoro:

Steps to reproduce: 
1. Buy Radiance
2. Burn enemy
note: reapplying Radiance-aura to an enemy with still existing Afterburn-stacks won't make the stacks disappear but will freeze the visual number of stacks the enemy has. it gets updated when it leaves the Radiance-radius.
Expected Result: Visible Aura-Icon and Stacks-Icon.
Actual Result: Invisible Aura-Icon and Stacks-Icon

https://cdn.discordapp.com/attachments/317271861966929921/317314914178039809/radiance.png

**Comment by Shushishtok** [comment]
Fixed.
