### ISSUE TITLE
Spellfencer dealing more damage than stated

### ISSUE THREAD

**Issue by AtroCty** [fcalife/dota_imba#342]
Reported by Voice of Resurgence: 

> Spellfencer does roughly twice as much damage as it should be doing
> Replication method: Pick Centaur, get Tutela and Pipe, get shot at by someone with spellfencer
>  I did all of the calculations fully including multiplicative damage reduction and damage amp and spellpower, numbers don't add up.

**Comment by lmk1988** [comment]
Might be Int increasing the damage dealt in magic

**Comment by Shushishtok** [comment]
Should be fixed now. Will reopen if it is still an issue.
