### ISSUE TITLE
Guardian Greaves not working under CM's aura when mana is under 60%

### ISSUE THREAD

**Issue by AtroCty** [fcalife/dota_imba#356]
Reported by osprofool:

> Steps to reproduce: create a CM and level aura, a random allie get guradian  greaves, mana under 60%
> Expected Result: guradian greaves not working
> Actual Result: guradian greaves not working
> Screenshot: http://i.imgur.com/mWdHC0c.jpg

**Comment by Shushishtok** [comment]
Fixed in the next iteration.
