### ISSUE TITLE
Techies mines explode after being destroyed

### ISSUE THREAD

**Issue by DoomAngelBlade** [fcalife/dota_imba#360]
I got 50 gold from mine i killed and it still got me dmgd.

This happened for me like 2 times for a game. I destroyed ~100 mines so it might be hard to reproduce this bug.

**Comment by sercankd** [comment]
It maybe another mine overlapping previous one.

**Comment by Shushishtok** [comment]
I can't reproduce it: I spawn a mine, kill it from far away (with sentry), then walk over - seems to be fine. As sercankd said, it may have been another mine on the exact same location, pulled from Stasis Traps.
