### ISSUE TITLE
Lycan doesn't get pushed by enemy Hurricane Pike

### ISSUE THREAD

**Issue by AtroCty** [fcalife/dota_imba#371]
Reported by ] KimSeJeong: 
```
: Summary: when i hurricane pike lycan only my hero pushed back but lycan as enemy not pushed back
Step for reproduce: use hurricane pike on lycan
```

**Comment by Shushishtok** [comment]
I can't reproduce it. Seems to be working just fine. That Lycan might have activated WQC or something along the lines to prevent the movement just as it was cast on it.
