### ISSUE TITLE
Roshan's wave doesn't hit the enemy and particle stays in the middle.

### ISSUE THREAD

**Issue by AtroCty** [fcalife/dota_imba#373]
Reported by AI:

> Repro:
> shrug I have yet to know what causes this. Possibly staying in middle/front? of roshan
> Expected: Wave hits the enemy and pushes them away.
> Now: Wave doesn't hit anything, particle is stuck in one place and roshan resumes his duties(bearbeitet)

**Comment by Shushishtok** [comment]
I don't see it being reproduced either by us or players. Closing until it gets reported again.

**Comment by AtroCty** [comment]
Fixed.
