### ISSUE TITLE
Mega Treads not providing Mega Bonus

### ISSUE THREAD

**Issue by AtroCty** [fcalife/dota_imba#375]
Reported by HulluPoro:

> Summary:  The Mega Treads don't give the Mega Bonus.
> Using Strength Mega Treads as example:
> Steps to reproduce:  
> 1. Buy Mega Boots
> 2. Switch from Agi to Strength Mode
> Expected Result: atleast +1000 HP from Strength and 500+ HP from Mega Bonus
> Actual Result: +1000 HP from Strength, no Mega Bonus

**Comment by Shushishtok** [comment]
Fixed.
