### ISSUE TITLE
Phantom Assassin's Blur and Slardar's Rain Cloud are bad particles

### ISSUE THREAD

**Issue by Shushishtok** [fcalife/dota_imba#385]
bad, bad particles. Let's kick them out! GTFO particles!

They cause fps drops and should be changed.

**Comment by sercankd** [comment]
68548552f273b14bacfc8d4aafd91740381b4107

**Comment by Shushishtok** [comment]
well Rain Cloud is half the issue too ;p

**Comment by Shushishtok** [comment]
Fixed Rain Cloud as well.
