### ISSUE TITLE
Angelic Alliance + respawn from Aegis resulting in a crash

### ISSUE THREAD

**Issue by AtroCty** [fcalife/dota_imba#398]
https://cdn.discordapp.com/attachments/317271861966929921/318940943518662656/unknown.png

**Comment by X-TheDark** [comment]
Also, posting this here for myself since it's relevant - Requested by Shush
```
While you're on it, do me a favor: make Angelic Alliance's passive disarm only apply once every 6 seconds, 25% chance, 2 seconds disarm. This means that if you applied disarm on an enemy, no new disarms will ever proc until the 6 seconds get through. If you want, make the modifier visible to show when the next disarm is available, but it's not required.
```

**Comment by X-TheDark** [comment]
Cannot reproduce the Respawn with Aegis part.

Tested on Warlock with Angelic Alliance and Aegis. On death - respawn as normal, no crashes.

**Comment by Shushishtok** [comment]
Meh. Will reopen if it occurs again. Might not be related to AA at all.
