### ISSUE TITLE
Sniper sometimes looses his vision after using his skills

### ISSUE THREAD

**Issue by AtroCty** [fcalife/dota_imba#410]
Reported by https://cdn.discordapp.com/attachments/317271861966929921/318427735200497665/20170528165952_1.jpg:

https://cdn.discordapp.com/attachments/317271861966929921/318427735200497665/20170528165952_1.jpg

**Comment by Shushishtok** [comment]
I can't see pictures (you're deleting them from discord!) and the description is too vague.
