### ISSUE TITLE
Pudge Hook make some heroes stuck forever

### ISSUE THREAD

**Issue by AtroCty** [fcalife/dota_imba#433]
Reported by HulluPoro: 

> Summary: Meat Hook can root heroes if Pudge casts a second Meat Hook while the first is moving the hero.
> Steps to reproduce: 1. Give Pudge an Aghs or Refresher Orb
> 2. Hook a target
> 3. Cast a second Hook in a different direction so that it can't hit the target
> Expected Result: first hook not stopping
> Actual Result: first hook stops and roots the target

**Comment by Shushishtok** [comment]
Seems to be fixed now.
