### ISSUE TITLE
If Rapier was purchased with full inventory, and is on stash, dying illusion drops rapier-duplicates.

### ISSUE THREAD

**Issue by AtroCty** [fcalife/dota_imba#434]
Reported by gandank the green: 

> if you're playing monkey king and have a full inventory and a divine rapier or trinity rapier in your stash and you ult, it spawns like 15 rapiers on the ground

**Comment by Shushishtok** [comment]
In general, anything that isn't a real hero shouldn't drop a rapier, including clones or Tempest Doubles.
