### ISSUE TITLE
Reconnected players and Observer have no UI

### ISSUE THREAD

**Issue by AtroCty** [fcalife/dota_imba#435]
Reported by MouJiaoZi

**Comment by Shushishtok** [comment]
Assigned to Cookie.

**Comment by RodneyMcKay** [comment]
It should be fixed now, sent the update to Shush, he did not updated imba test yet. Testing tomorrow!

**Comment by Shushishtok** [comment]
Seems to be working in of the 95% cases. There are still some rare cases where this does not work. Closing for now until further reports regarding this matter.
