### ISSUE TITLE
Battle Fury should deal a real cleave attack

### ISSUE THREAD

**Issue by AtroCty** [fcalife/dota_imba#444]
Right now it deals pure damage in an AoE, thus being affected by spell AMP, too.
Rewrite in LUA would be recommended.

**Comment by Shushishtok** [comment]
Isn't Bfury reverted to vanilla?

**Comment by X-TheDark** [comment]
Shush is correct, spell amplification does not affect battlefury cleave damage.

Battle Fury only, 1% spell amp.
![bfonly](https://cloud.githubusercontent.com/assets/2188139/26716948/2a0397b8-4784-11e7-96a7-cbd785899538.png)

Battle Fury + Aether + 4 Mystic Staves, spell amp 14.1%
![bfandspellamp](https://cloud.githubusercontent.com/assets/2188139/26716973/3e7f8bfc-4784-11e7-9953-bd4a0bf8dd45.png)

**Comment by Shushishtok** [comment]
Agreed, so we just need to IMBAfy it later.
