### ISSUE TITLE
pudge bug

### ISSUE THREAD

**Issue by lmk1988** [fcalife/dota_imba#455]
- [x] ~~you can permanently root someone if you hit them with hook more than once while they are still flying~~ (fixed)

- [x] After casting hook, if you use refresher orb to cast the second hook, it ends prematurely. (ends when first hook ends)

- [x] After learning the 3 hooks talent. If you melee hook a hero, it only comes out as 1 hook to skewer. Or if you only hit the enemy with the side hook, the middle hook disappears
![image](https://cloud.githubusercontent.com/assets/4424781/26753042/455f5ae4-4890-11e7-8c5e-15b7f1bcd592.png) (fixed by @Wouterz90)

**Comment by Shushishtok** [comment]
Refresher Hook: seems to be the same issue in vanilla Dota, and a rare enough case. We can ignore it for now unless somehow Pudge with Refresher becomes the new meta or something.
