### ISSUE TITLE
Skywrath Mage Concussive Shot

### ISSUE THREAD

**Issue by FDSATREW** [fcalife/dota_imba#457]
In old times in imba 6.88 this skill create circle effect on ground when hit enemy that shows "second aoe slow effect" aoe, but now it's shots projectiles from [nothing](https://image.ibb.co/cXXsCa/image.png) to enemies.

**Comment by Shushishtok** [comment]
It was reworked to make the actual hero hit by Concussive Shot project his own Concussive Shot.

This is intended. Please ask before opening this kind of issues.
