### ISSUE TITLE
Need some guide/help to start contributing (build/debug)

### ISSUE THREAD

**Issue by avilv** [fcalife/dota_imba#47]
I would like to start contributing,
but im having trouble importing this project to dota workshoptools

currently im copying it to game\dota_addons
it does seem to start, but i cannot use  dota_launch_custom_game to launch it

i see a bunch of entries in gitignore
are there any assets i need to copy over that are required?

any help would be appreciated :)

**Comment by fcalife** [comment]
Hello!

This github wasn't set up properly initially - it was just made as a kind of backup, should anything happen to my local files.

My updates to it were never consistent, and over time, they grew even more sparse.

Recently, many people have expressed the desire to help here, so, with the next IMBA patch, i will be adding all the necessary files to run it locally on your machine, as well as making it easier to contribute.

Thank you very much for being interested in helping! :)

Best regards

**Comment by avilv** [comment]
alright, im currently using a decompressed vpk to develop (not that easy..) are you managing to debug this somehow using eclipse LDT? having trouble with the set up..

i see you merged my pull request already ( pudge fix ) , feeling hopeful now :)
ill try and stick to specific bug-hunting for now until the git repo is complete (just ask if you need help setting things up)

**Comment by sercankd** [comment]
debugging is done through vconsole 2, its all you need. also it shows on game screen with red text if there are errors.

**Comment by fcalife** [comment]
Please check if the files are OK for you now. Thanks!
