### ISSUE TITLE
Bloodseeker blood footprints

### ISSUE THREAD

**Issue by lmk1988** [fcalife/dota_imba#479]
If blood seeker gets ruptured himself (due to enemy or spell reflect) he will get permanent blood footprints

**Comment by X-TheDark** [comment]
Can't reproduce. Are you sure the blood footprints aren't just part of Thirst? When you level it up, Bloodseeker gets the bloody foots effect thing.

**Comment by Shushishtok** [comment]
Agree with X-TheDark, I can't reproduce as well. Tell me if you got some further issues with it and I'll reopen if necessary.
