### ISSUE TITLE
Anti-Mage Rework

### ISSUE THREAD

**Issue by X-TheDark** [fcalife/dota_imba#512]
Mana Break: When an attack reduces the target's mana below 75%, 50% or 25%, it explodes, dealing a portion of the max mana pool of the target to it and enemies in 380 AoE around it. This effect always procs when the target has 0 mana.

Blink: Adjust current mana burn numbers from 0/0/0/0/5/10/15% to 8/12/16/20/25/30/35%.
Update tooltip "actual mana" to "current mana".

Spellshield: now only reflects spells from units 2500 AoE away.

------------------------------------------------

TALENTS:
Remove:
-1 Blink CD.
+1 Spell Shield duration.
+10% Blink mana burn.
+35 Mana Break damage.
-50 Mana Void CD.

Apply:
1. Blink gains 3 charges.
2. Spell Shield can be used even while stunned.
3. Blinking grants a 1 second magic immunity shield.
4. When activating Mana Void, the explosion is delayed for 2 seconds. Each point of mana lost while this is in effect is worth as 2x missing mana points.
5. Mana Break attacks burn mana of nearby enemies in 500 AoE, equal to 30% of the mana burned. This is shown through a blue cleave effect.

**Comment by fcalife** [comment]
Random comment: talent 5 is weak (damage/mana per second removal is much weaker than what AM already does by simply hitting people) and can easily worsen game lag due to spawning several timers (think high attack speed AM). Would not recommend.

**Comment by Shushishtok** [comment]
Got an alternative talent?

Regarding the several timers - it can be solved by assigning the modifier on Anti Mage, indexing mana pools to it, and running one timer. Code-wise this isn't a problem, but I do agree that it might not be as good as it sounds.

**Comment by Shushishtok** [comment]
Done!
