### ISSUE TITLE
Bane Rework

### ISSUE THREAD

**Issue by X-TheDark** [fcalife/dota_imba#514]
Enfeeble:
No longer reduces stats.
lower Cooldown, lower Effects, stackable, up to 5 stacks. Vision is turned off and on like survival game, increasing intensity per stack. The more stacks a target, the more vision it can lose when it triggers.

Brain Sap:
No longer has Addelbrain.
When sapping a target, the modifier sets the target's intelligence and mana at 0 for 3 seconds.
Consumes Enfeeble stacks on the target, and deals bonus damage to it depending on the stack count.

Nightmare:
No longer has Baneful Visions.
After waking up from a nightmare, the affected target has 0 vision range for a moderate duration, and cannot see anything himself.

Fiend's Grip:
Each tick consume one stack of Enfeeble. Each consumption of Enfeeble summons a demon (models/items/courier/onibi_lvl_05/onibi_lvl_05_flying.vmdl) that is colored "evil purple". Demons are invincible, untargetable, and last for the remaining duration of Fiend's Grip, including the extra effect. They tether themselves to the target and each steal health and mana from it.

Generic Talent: give Bane mana regen instead of something else.

---------------------------------------------------
TALENTS:

Remove:
+3 Baleful Vision duration
+1.5 Addebrain duration
+150 Brain Sap damage
+10 Enfeeble duration
+2 Fiend's Grip
+100 damage reduction from Enfeeble

Apply:
1. Grants 2 Enfeeble stacks when Nightmaring a target.
2. Enfeeble is now cast in a 450 AoE to all targets around the main target.
3. Fiend's Grip is no longer channeled. Fiend's Grip stops if Bane dies or become disabled. For the duration of the 'channel', Bane is visible to the enemy. If possible - it also keeps the channel animation and sounds.
4. Enfeeble causes the target to lose 10% of his stats. This effect increases by 10% for each Enfeeble stack it has.
5. Brain Sap casts summons a Baby Bane which applies a Baby Fiend's Grip on the target. Baby Grip deals 25% damage, mana, and lasts for 0.5 seconds. Baby Grips does not interact with Enfeebles. Baby Banes are invincible and uncontrollable. They stay for 1 second after finishing Baby Grip, then disappear.
6. Nightmare also mutes items for enemies affected for 3 seconds.

**Comment by brandonsturgeon** [comment]
I'm loving these! Very creative and fun.

It's about time Bane got reworked :) It's too easy to win games with him.

**Comment by Shushishtok** [comment]
This isn't the reason Bane is being reworked. He's deemed very not-IMBA, as you don't really "notice" his IMBA effects. They're there, yes, but you as a player never see it.

**Comment by brandonsturgeon** [comment]
He's imbalanced, but not IMBA-y :)

The stat reduction on enfeeble is so good, it really helps against mega treads.

Regardless of the reason, all of these issues are well written and creative!

**Comment by Arkandos** [comment]
Brainsap setting Int and mana to 0 seems pretty awful, especially for 3 whole seconds.

**Comment by Shushishtok** [comment]
It's a psuedo silence that also doesn't allow you to regenerate mana or use items that requires even small amounts of mana. I don't see how it's awful.

**Comment by fcalife** [comment]
Comments/suggestions:

- enfeeble stacking mechanic has almost zero synergy with bane's aghs - you need some time to stack enfeeble up, while brain sap's cool down becomes minuscule with aghs.
- brain sap + refresh + brain sap (or simply ages brain sap) will leave people at zero intelligence if coded carelessly, watch out for that easily avoidable interaction;
- it's very rare for bane to have time to fire off his abilities during a team fight (ideal scenario for him), much less to have time to spam enfeeble before using fiend's grip on someone. I fear the stacking effect will rarely come into play.
- talent 3: no longer channeled, but interrupted if bane is disabled? this sounds like pug's life drain, but without the visual effect - I'd add some visual "hint" of what's happening, so people know to stun bane, or would make bane visible to the enemy team for the duration of the fiend's grip (which already happens in the channeled version).
- talent 4: as written, initial effect (30% stat reduction) too strong versus the scaling (30/35/40/45/50). Would suggest 10% per stack.
- talent 6: nightmare fully disables units, so I don't see the point of muting their items in addition.

Best regards!

**Comment by Shushishtok** [comment]
>enfeeble stacking mechanic has almost zero synergy with bane's aghs - you need some time to stack enfeeble up, while brain sap's cool down becomes minuscule with aghs.

I'm wary of this, but still willing to give this is a try. It means people will keep a safe distance and use Enfeeble on a target, while using Nightmare to keep them down, as Enfeeble won't wake them up. This can breed a few strategies, so I'd like to see what happens.

>brain sap + refresh + brain sap (or simply ages brain sap) will leave people at zero intelligence if coded carelessly, watch out for that easily avoidable interaction;

It should be just a modifier that refreshes and grants them a negative value of their intelligence. Should be fine. *Should*.

>it's very rare for bane to have time to fire off his abilities during a team fight (ideal scenario for him), much less to have time to spam enfeeble before using fiend's grip on someone. I fear the stacking effect will rarely come into play.

Same as the first bullet. Would like to wait and see.

>talent 3: no longer channeled, but interrupted if bane is disabled? this sounds like pug's life drain, but without the visual effect - I'd add some visual "hint" of what's happening, so people know to stun bane, or would make bane visible to the enemy team for the duration of the fiend's grip (which already happens in the channeled version).

Agreed. Making Bane visible sounds good. Also, we might want to make him keep doing the channel animation while he's not doing anything else.

>talent 4: as written, initial effect (30% stat reduction) too strong versus the scaling (30/35/40/45/50). Would suggest 10% per stack.

Agreed.

>talent 6: nightmare fully disables units, so I don't see the point of muting their items in addition.

This applies to 3 seconds *after* Nightmare ends.

**Comment by Arkandos** [comment]
Yeah I see now. I somehow thought BKB had a manacost, my bad.

**Comment by Shushishtok** [comment]
Even if it had a mana cost, what does that has to do with how awful (or not awful) this mechanic is?

**Comment by brandonsturgeon** [comment]
Maybe I'm off-point here, but I think @Arkandos is saying that setting their mana to 0 is effectively muting an item (bkb).

**Comment by Shushishtok** [comment]
Done!
