### ISSUE TITLE
Bloodseeker Rework

### ISSUE THREAD

**Issue by X-TheDark** [fcalife/dota_imba#515]
Scepter reverted to Rupture having 2 charges.

--------------------------------------------

TALENTS:
Remove:
+25% Cooldown refresh Blood Rite.
+2 thirst on-hit damage bonuses duration.
+25% attacking/casting on Rupture self-damage.
+5% ms, +26 damage max bonus on Thirst.

Change: +700 cap to 1700.

Apply:
1. Blood Rite applies Rupture on targets in it, then pushes them out of it. Rupture is then removed (unless target already had Rupture). (against 3rd talent)
2. Blood Rite's silence becomes unpurgable.
3. Blood Rite is cast in three circles, one to the right of the target point, one to the left and one in front of the cast point. (against 1st talent)
4. When killing an enemy unit that has Bloodrage, the killer gets a buff for 3.5 seconds that grants 100% movespeed bonus. Killing an enemy hero doubles the duration. This effect can occur for both teams!

**Comment by fcalife** [comment]
comments/suggestions:

- talent 3 arguably makes it harder to hit blood rite in certain situations. I'd use another geometry, that includes 100% of the original area, or make it unit-targetable (friend or enemy), in exchange for a 25% smaller radius (normal AOE if cast on ground).
- talent 4 is awesome but 1.5sec is barely enough time to notice you became sonic. It's like "OH SHIT I'M A GOD - oh god it's over already). I'd also make it +100% MS so BS benefits more from it (as he can have over 500ms from thirst already).

**Comment by Shushishtok** [comment]
>talent 3 arguably makes it harder to hit blood rite in certain situations. I'd use another geometry, that includes 100% of the original area, or make it unit-targetable (friend or enemy), in exchange for a 25% smaller radius (normal AOE if cast on ground).

I think it's fine to lose a bit of the original area if you get two of them. Complicates enemies' escape routes. I feel good players would be able to use it to their advantage.

>talent 4 is awesome but 1.5sec is barely enough time to notice you became sonic. It's like "OH SHIT I'M A GOD - oh god it's over already). I'd also make it +100% MS so BS benefits more from it (as he can have over 500ms from thirst already).

Agreed.

**Comment by Shushishtok** [comment]
Done!
