### ISSUE TITLE
Centaur Rework

### ISSUE THREAD

**Issue by X-TheDark** [fcalife/dota_imba#517]
Return: Tower attacks do not trigger Bulging Hide (doesn't refresh or increase stacks).

------------------------------------------

TALENTS:
Remove:
+85 Hoof Stomp damage.
+110 Double Edge radius.
+1 Arena/Hoof Stomp stun duration.
+5 Bulging Hide damage block per stack.

Apply:
1. Double Edge's damage (both self and against enemies) increases by 2 for each point of strength.
2. Hoof Stomp's Gladiator Arena is always centered on Centaur's location. This effect stops if Centaur moves more than 600 range in one instance. (Blink, TP).
3. Stampede grants 75% Tenacity to everyone affected for the duration.
4. Return's Bulging Hide gains stacks from all auto attacks, or any kind of damage above 100.

**Comment by Wouterz90** [comment]
I'm not able to make the arena moving along with me. Tried several things with the particle editor but to no avail.

for 4. Return's Bulging Hide gains stacks from all auto attacks, or any kind of damage above 100.
If I understand correctly it is now this: Bulging Hide gains stacks from all auto attacks?  But it just doesn't seem right. So if someone could clarify it would be nice.
