### ISSUE TITLE
Clinkz Rework

### ISSUE THREAD

**Issue by X-TheDark** [fcalife/dota_imba#518]
Strafe: Attack speed and attack range scale in early levels. Those bonuses are always gained. When mounted, those bonuses are doubled!

Searing Arrows: scale damage better: from 30/40/50/60/65/70/75 to 30/45/60/75/100/125/150.
Active component lasts 10 seconds and reduces armor of the target by 1 per second.
Reduce the cooldown of the Mega Flaming Arrow.

Death Pact: when Clinkz uses Dark Pact on a creep, that creep dies and becomes "spirited", forced to wander behind him for the duration. That creep grants Clinkz its own attack damage and armor. Spirited creeps die within 5 attacks on them, or when the duration ended. The bonuses from the spirit are lost (the normal pact bonus does not).
When using on an enemy hero, killing him while under Death Pact's effect grants you the same bonuses until the end of the duration!

--------------------------------------
TALENTS:

Remove:
+200 spook radius.
+150 attack range.
+35 searing arrows damage.
+80 attack speed.
+50% Death Pact bonuses.

Apply:
1. Death Pact Spirits are now capable of attacking. They fire 'spiritual' projectiles at Clinkz's main target. Spirits always have Clinkz's attack range + 100. Spirits have 150 attack speed, and their damage is equal to their original unit's damage.
2. When moving in Skeleton Walk, if Clinkz goes through an enemy, Clinkz loses his invisibility, but the enemy becomes rooted for 3 seconds.
3. Strafe can be cast on yourself, rooting your for the duration, but granting 4x the attack range bonus of Strafe.
4. Whenever Clinkz attacks, he gains a 20% chance to fire a second Searing Arrow at the same target.
5. Moving near an enemy (450 AoE) while Skeleton Walking grants Clinkz 25% bonus move speed, until no enemies are nearby.

**Comment by fcalife** [comment]
comments/suggestions:

- I don't have much specific to say, except that he does a **lot** of damage. Like, a LOT. His numbers are crazy.
- talent 2 is arguably a nerf, since sometimes you can't avoid running through enemies
- talent 3 is crazy strong
- talent 4 is a fancy way to add a crit. except it stacks with crits. LOTSA DAMAGE. beware.

**Comment by Shushishtok** [comment]
>I don't have much specific to say, except that he does a lot of damage. Like, a LOT. His numbers are crazy.

You always used to say that numbers are the easiest thing to change. ;p

>talent 2 is arguably a nerf, since sometimes you can't avoid running through enemies

True, but because of root + spook, they cannot do anything for 3 seconds. Can be used to turn the tables sometimes.

>talent 3 is crazy strong

And I love it. Grants 1000 attack range at max levels. Still needs vision though.

>talent 4 is a fancy way to add a crit. except it stacks with crits. LOTSA DAMAGE. beware.

Yes please. :D

**Comment by IamInnocentX3** [comment]
Hey'all! I love all the changes applied to this. But talent 5 doesn't sound useful so I suggest a buff, increase the AOE from 450 to 600.

Here's an idea I suggest that could replace Talent 5:

Skeleton Walking when there are no enemies nearby (Spook Radius) grants Clinkz 20% bonus move speed, until when there are enemies nearby. Also Increases Spook duration by 20%.

**Comment by Shushishtok** [comment]
>Skeleton Walking when there are no enemies nearby (Spook Radius) grants Clinkz 20% bonus move speed, until when there are enemies nearby.

I agree to the proposal. However, I do not agree to the duration increase. It has nothing to do with the idea behind the talent.

**Comment by IamInnocentX3** [comment]
Alright, another question. Does Searing Arrow's Active vision bonus go along with armor reduction for 10 seconds? Or remain the same as 3.5 4 4.5 5 6 7 8 seconds?

**Comment by Shushishtok** [comment]
1. Active. They are not passive at any time.

2. It should go along with the armor reduction duration.

**Comment by Shushishtok** [comment]
Done!

**Comment by hulluporo** [comment]
possibly a better tiering of the talents:
lvl10: Skeleton Walk's MS persists for 5s // Clinkz gains extra MS when Skeleton Walking close to enemies

lvl20:  Skeleton Walking through an enemy roots target, Clinkz loses invis // Searing Arrows active gets 400 AoE

lvl30: Strafe can be self-cast for 4x range-bonus but roots // Death Pact Spirits can now attack

lvl40: Searing Arrow has 20% chance to fire another arrow // 10% extra Deathpact bonuses that last until deat if target is killed inside 5s
