### ISSUE TITLE
Crystal Maiden Rework

### ISSUE THREAD

**Issue by X-TheDark** [fcalife/dota_imba#519]
-------------------------------
TALENTS:

Remove:
+20% Freezing Field slow.
+175 Crystal Nova Radius.
+1.5 Frostbite duration.
-6 Icy Touch CD.
+260 Crystal Nova damage.

Apply:
1. Freezing Field's no longer drops projectiles - instead, Crystal Maiden channels for up to 10 seconds. When the channel ends (or interrupted), a huge icicle arrives at the cast area. The icicle explodes violenty, breaking into shards that are evenly distributed between all nearby enemies in range, dealing usual damage in the target's AoE. Each 0.1 seconds of a channel generates one shard.
2. Icy Touch causes a 100% movement speed slow that is slowly regained over 6 seconds.
3. Freezing Field constantly Frostbites enemies in it duration the duration of the spell - a unit is Frostbitten once every 3 seconds after the effect on it ended. Additional Frostbites procced by this talent have their duration halved.
4. Enemies hit by Crystal Maiden's abilities gain a debuff that slows them by 15%/15 move/attack speed for 3 seconds. Can be refreshed.
5. Crystal Nova's Snowfield grants 10% damage reduction and increases health regeneration by 20.

**Comment by fcalife** [comment]
comments/suggestions:

- talent 1 combined with aghs is severely abusable in the sense that enemies don't know they're gonna get WTF-thermonuclearairbursted until it has already hit them. I'd maybe cause half of the normal effect to happen, while half of it is stored for the final hit.
- talent 3 is really strong. *really* strong. Compare black hole to this.

**Comment by Shushishtok** [comment]
>talent 1 combined with aghs is severely abusable in the sense that enemies don't know they're gonna get WTF-thermonuclearairbursted until it has already hit them. I'd maybe cause half of the normal effect to happen, while half of it is stored for the final hit.

True. However, there's a huge weakness to this - they need to be stationed at the cast location for the channel time, together. I mean, what are chances of channeling the full 10 seconds on enemies without them moving away -  not because they saw you, but because of game flow? I'd like to test this and see. Could be a level 40 talent.

>talent 3 is really strong. really strong. Compare black hole to this. 

I actually am comparing it to Pit of Malice, where you can be rooted again if you're still in the AoE.
I'd add a 50% duration reduction to additional frostbites.

**Comment by natanfudge** [comment]
That cm talent looks fucking badass
