### ISSUE TITLE
Dazzle Rework

### ISSUE THREAD

**Issue by X-TheDark** [fcalife/dota_imba#520]
Poison Touch: Better scaling, mostly numbers.

Shallow Grave: Nothl Protection cooldown to 30 seconds, fixed.
When taking fatal damage under Nothl Protection and Shallow Grave, the target also gains 1 armor and 2% magic resistance for each damage instance. The armor and magic resistance bonuses last for 5 seconds after Shallow Grave ends.

Shadow Wave: Shadow Wave can be cast on an enemy unit. Doing so makes the wave bounce between enemies, dealing damage to them and healing allies that are near them. Allies can be healed multiple times per wave.
When a Shadow Wave deals damage to a Poison Touched enemy, all further enemies that the wave bounces to get affected by the debuff as well.  (full duration)
Shadow Wave heal/damage radius change to 250.

Weave: Every 4 seconds, Sub-Weaves are cast in the original location, over the duration. Units that do not yet have the buff/debuff get it normally. Sub-Weaves instantly shifts the armor of the target. The armor keeps stacking normally until the duration ends. 

New scepter effect: Grants a new ability: Resurrection.

Resurrection: Can only be cast on dead allies teammates, used through the player portraits on the top bar. After a 3 seconds delay, the teammate respawns with full health and mana. Resurrected heroes respawn near Dazzle's location. Cannot be used on Disable Help players.

Has global range, 250 mana cost, 100 seconds cooldown.

-------------------------------------------------------------
TALENTS:

Remove:
+175 Shadow Wave bounce distance
+65 Shadow Wave damage radius
-15 Weave CD.
+60 Shadow Wave damage/heal
-15 Nothl Protection CD.
-5 Poison Touch CD.
Shallow Grave costs no mana.

Apply:
1. Shadow Wave bounces in a 1 second delay between each target. However, each target can be healed again by a bounce if 5 seconds have passed. A maximum of 3 bouncing waves can exist at the same time.
2. Shadow Wave bounces on allies can heal surrounding allies in the damage radius.
3. All excess damage stored by Shallow Grave/Nothl Protection is released as a Healing Wave, healing all nearby allies for 50% of excess damage. This wave does not damage enemies.
4. After Poison Touch's poison has finished setting in, every 3% target's max health damage the target takes, it slows the target by 3%. Can scale up to 80%.
5. Enemies that interact in any way a unit that has the Poison Touch debuff get the debuff as well. Interactions are using a skill or an item on the target.
6. Nothl Protection is now applied on every allied hero in 900 AoE. Nothl Protection triggers automatically on a fatal strike and lasts 1.5 seconds. It needs to recharge for the same duration of Dazzle's own Nothl Protection.
7. Weave now fully affects buildings as well.

**Comment by fcalife** [comment]
comments/suggestions:

- shadow wave/poison touch is *really really* strong. I wouldn't say gamebreakinig strong but it's really fucking strong. beware.
- talent 1: good luck coding that! really cool tho.
- talent 2 is insane on clumped up enemies. its echo slam on super steroids. Please think it over carefully!
- talent 4: would maybe make this scale with target's max health (i.e. 3% slow every 3% of max health taken as damage, or similar. vaguely similar to timber's charm slow).
- talent 6 is a bit too similar to WK's wraith aura?

**Comment by Shushishtok** [comment]
>shadow wave/poison touch is really really strong. I wouldn't say gamebreakinig strong but it's really fucking strong. beware. 

Really? I think it's conditional. It's good as a situational occurrence. What are you think is so strong about it?

>talent 1: good luck coding that! really cool tho. 

Shouldn't be a problem. Indexing in an projectile_extra_data does the job well.

>talent 2 is insane on clumped up enemies. its echo slam on super steroids. Please think it over carefully!

I see your point. Maybe just retain the healing aspect, for a possible echo slam healing?

>talent 4: would maybe make this scale with target's max health (i.e. 3% slow every 3% of max health taken as damage, or similar. vaguely similar to timber's charm slow).

Good idea.

>talent 6 is a bit too similar to WK's wraith aura?

Not quite. Dying in WK's Wraith Aura means you're dead, period, do what you can for the duration. This can actually save you from death, and more than that, in certain situations (Troll is max-speed attacking you? lul) be returned to full health.

**Comment by Shushishtok** [comment]
Done!
