### ISSUE TITLE
Drow Ranger Rework

### ISSUE THREAD

**Issue by X-TheDark** [fcalife/dota_imba#529]
-------
TALENTS:
Remove:
+1 Frost Arrows duration
+6% Trueshot Aura damage
+400 Gust range
+250 Deadeye bonuses
+30 agility when ult is active

Apply:
1. Gust can be self cast, making a wave that moves Drow Ranger herself forward. This wave silences all enemies that it comes in contact with normally. 
2. After casting Gust, all auto attacks hitting the target casts a small Gust for 5 seconds. This small gust wave pushes the target back 50 units, deals no damage, and does not silence.
3. Each Chilled enemy grants drow +10 flat movespeed bonus for the duration. Stacks with itself, depending on amounts of Chill stacks on enemies.
4. While Trueshot Aura is active, Drow gains agility equal to 5% of every allied hero's agility. 
5. While Marksmanship is active (not disabled by nearby enemies), Drow Ranger emits an aura on nearby allies that makes their attack chill their targets, slowing them by 15%.

**Comment by Lindbrum** [comment]
Done!
