### ISSUE TITLE
Enigma Rework

### ISSUE THREAD

**Issue by X-TheDark** [fcalife/dota_imba#530]
Gravity Well: Removed entirely. Singularity moved to Black Hole.

Malefice: 
1. Now always pulls target enemy towards the strongest source: Black Hole, then Midnight Pulse, then Enigma.
2. Each 25% health that the enemy has when applying Malefice on it increases the duration by 2 seconds.
3. Eidolons' attacks causes the next instance of Malefice's stun to be increased a bit.

Midnight pulse:
1. Now always pulls all targets in range towards it, if they're not affected by Black Hole.
2. Eidelons in Midnight Pulse gain bonus health regeneration. This effect lingers for 3 seconds after leaving Midnight Pulse's AoE.

Black Hole: 
1. Black Hole constantly pulls all enemies in a 1200 AoE towards it. The closer they are to the Black Hole, the stronger the pull. The pull has a minimum of 75 pull power.
2. Each enemy hero that it caught within Black Hole increases Singularity stacks by 1 for each damage instance. Singularity stacks are consumed on the next Black Hole cast, increasing the pull power by 20 per stack, the Black Hole's AoE by 25, and the pull AoE by 50.

Demonic Conversion:
1. Shrink tooltips:
Transforms a creep into 3 eidolons.  Eidolons heal completely and multiply after 6 attacks.  ENDLESS: Eidolons can multiply infinitely, but consecutive splits require 3 more attacks.  PRIMORDIAL SHARD:  Eidolons gain a percentage of Engima's Health, Armor, Damage, Attackspeed, and Movespeed.  VOID MASS: Eidolons' attacks amplify the pull effects of Engima's spells by 7%, this stacks between Eidolons, but indivudal Eidolons' attacks only re-apply the effect.

--------------
TALENTS:
Remove:
+2 malefice duration
+225 black hole cast range
+15% eidolons stats
+80 Black Hole radius
+15% Gravity Well
+1 Black Hole duration

Change:
Malefice is applies on all enemies in 215 range -> Malefice is applies on all enemies in 400 range.

Apply:
1. Each Singularity stack consumed now decreases Black Hole's cooldown by 2 seconds.
2. When Enigma dies, a Blackhole is cast on its location of death with half duration. Does not consumes Singularity stacks.
3. Midnight Pulse doubles its AoE over the duration.
4. Enigma has a constant AoE Midnight pulse around him. Stacks with regular pulse.
5. True malefice - malefice now triggers Black Holes instead of just stunning.
6. Whenever Enigma casts a spell, his void energy grants him magic immunity for one second. Duration stacks with itself.

**Comment by Wouterz90** [comment]
Some questions
1. Does this work retroactive?
2. Does this collect Singularity stacks?
5. What does this mean?

**Comment by Shushishtok** [comment]
Done!
