### ISSUE TITLE
Faceless Void Rework

### ISSUE THREAD

**Issue by X-TheDark** [fcalife/dota_imba#531]
Chronosphere:
1. Proccing Time Lock to an enemy affected by Chronosphere procs it on all enemies inside it.
2. Adds one second to enemy's cooldowns per enemy caught in Chronosphere.

-----------------------
TALENTS:
Remove:
+1 backtrack time
+5% attack/move speed in time dilation
+600 Q cast range
+0.05 chrono
+0.5 chronocharges

Apply:
1. Time Dilation grants Faceless Void 5% chance to backtrack damage instances per enemy ability spell affected, up to 50% chance. Lasts 6 seconds.
2. Time Locking enemies with the Time Dilation debuff increases their active spells' CD by 0.5s while decreasing all of Voids cooldowns by 0.5s.
3. Time Lock now causes mini chronospheres with 180 AoE, capable of freezing enemy units close to the main target.
4. Time Lord bonuses are doubled when Faceless Void is inside a Chronosphere. 
5. Chronosphere causes Faceless Void attacks to cleave 600 units away.

**Comment by X-TheDark** [comment]
Just so we're clear. The Chronosphere's 2nd point adds also adds it's own duration to the cooldown, correct? Otherwise there's little point to just making the skills go on cooldown for 1/2/3/4 etc seconds, if the cooldown will end in the Chronosphere.

**Comment by natanfudge** [comment]
https://github.com/fcalife/dota_imba/pull/558
close this^^

**Comment by Shushishtok** [comment]
Done!
