### ISSUE TITLE
Pudge Balance rework

### ISSUE THREAD

**Issue by Shushishtok** [fcalife/dota_imba#540]
Rot: Maximum radius from 400 to 500.

Flesh Heap: 
1) Each stack increases magic resistance by 2%, up to 30%.
2) Each stack increases Meat Hook's damage by 5, up to 200. 
3) Landing the killing blow grants two stacks of Flesh Heap.

Dismember:
1) Pudge always heals from Dismember, even if the target is spell immune.

TALENTS:
Remove those talents:
+200 Hook range.
+20% Flesh Heap Magic resistance.
+120 Rot damage
+1.75 strength per Flesh Heap stack
+2 Dismemeber duration.

Add those talents instead:
1. Meat Shield: Each 5 stacks of Flesh Heaps grants Pudge a stack of Meat Shield. When Pudge is attacked, he consumes one stack to block 100 damage from it. Meat Shield stacks recharge independetly, 10 seconds after being depleted. 
2. Rot deals 40 more damage for each 5% health pudge is missing.
3. Dismember disarms the target. The disarm duration scales with how long Dismember was channeled. Unpurgable.
4. Cleaver can now pierce through enemies, damaging and affecting all enemies in a straight line.
5. Meat Hooked units now destroy trees in the hook path. Each tree the hooked units go through deals 120 physical damage to them.

**Comment by Wouterz90** [comment]
1.
Should there be a minimal amount? Is it really only limited to attacks and not spells?
5.
Does that mean that trees hit before units count? Does it only still only deal damage on impact so trees being destroyed later don't deal damage?

**Comment by Shushishtok** [comment]
Done by @Wouterz90 , closing!
